<a href="https://colab.research.google.com/github/jessicamadridmejia/Cheat-Sheets/blob/master/1_Python_for_Data_Science_Cheat_Sheet_Python_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python for Data Science

## Variables and Data Types

### Variable Assignment

In [1]:
x=5
x

5

### Calculations With Variables

In [2]:
# Sum of two variables
x + 2

7

In [3]:
# Subtraction of two variables
x - 2

3

In [4]:
# Multiplication of two variables
x * 2

10

In [5]:
# Exponentiation of a variable
x ** 2

25

In [6]:
# Remainder of a variable
x % 2

1

In [7]:
# Division of a variable
x / 2

2.5

In [8]:
# Division of a variable
x // 2

2

### Types and Type Conversion

In [9]:
# Variables to strings
str(5)

'5'

In [10]:
# Variables to integers
int('10')

10

In [11]:
# Variables to floats
float('8')

8.0

In [12]:
# Variables to booleans
bool('')

False

In [13]:
# Variables to booleans
bool('g')

True

## Asking For Help

In [0]:
# help(str)

## Strings

In [15]:
my_string = 'thisStringIsAwesome'
my_string

'thisStringIsAwesome'

### String Operations

In [16]:
my_string * 2

'thisStringIsAwesomethisStringIsAwesome'

In [17]:
my_string + 'Innit'

'thisStringIsAwesomeInnit'

In [18]:
'm' in my_string

True

In [19]:
my_string[3]

's'

In [20]:
my_string[4:9]

'Strin'

### String Methods

In [21]:
# String to uppercase
my_string.upper()

'THISSTRINGISAWESOME'

In [22]:
# String to lowercase
my_string.lower()

'thisstringisawesome'

In [23]:
# Count String elements
my_string.count('w')

1

In [24]:
# Replace String elements
my_string.replace('e', 'i')

'thisStringIsAwisomi'

In [25]:
# Strip whitespaces
my_string = 'thisStringIsAwesome '
my_string.strip()

'thisStringIsAwesome'

## Lists

In [0]:
a = 'is'
b = 'nice'
my_list = ['my','list',a, b]
my_list2 = [[4,5,6,7], [3,4,5,6]]

### Selecting List Elements

#### Subset

In [27]:
# Select item at index 1
my_list[1]

'list'

In [28]:
# Select 3rd last item
my_list[-2]

'is'

#### Slice

In [29]:
# Select items at index 1 and 2
my_list[1:3]

['list', 'is']

In [30]:
# Select items after index 0
my_list[1:]

['list', 'is', 'nice']

In [31]:
# Select items before index 3
my_list[:3]

['my', 'list', 'is']

In [32]:
# Copy my_list
my_list[:]

['my', 'list', 'is', 'nice']

#### Subset List of Lists

In [33]:
# my_list[list][itemOfList]
my_list2[1][0]

3

In [34]:
# my_list[list][itemOfList]
my_list2[1][:2]

[3, 4]

### List Operations

In [35]:
my_list + my_list

['my', 'list', 'is', 'nice', 'my', 'list', 'is', 'nice']

In [36]:
my_list * 2

['my', 'list', 'is', 'nice', 'my', 'list', 'is', 'nice']

### List Methods

In [37]:
my_list

['my', 'list', 'is', 'nice']

In [38]:
# Get the index of an item
my_list.index(a)

2

In [39]:
# Count an item
my_list.count(a)

1

In [40]:
# Append an item at a time
my_list.append('!')
my_list

['my', 'list', 'is', 'nice', '!']

In [41]:
# Remove an item
my_list.remove('!')
my_list

['my', 'list', 'is', 'nice']

In [42]:
# Remove an item
del(my_list[0:1])
my_list

['list', 'is', 'nice']

In [43]:
# Reverse the list
my_list.reverse()
my_list

['nice', 'is', 'list']

In [44]:
# Append an item
my_list.extend('!')
my_list

['nice', 'is', 'list', '!']

In [45]:
# Remove an item
my_list.pop(-1)
my_list

['nice', 'is', 'list']

In [46]:
# Insert an item
my_list.insert(0,'!')
my_list

['!', 'nice', 'is', 'list']

In [47]:
# Sort the list
my_list.sort()
my_list

['!', 'is', 'list', 'nice']

## Libraries

### Import libraries

In [0]:
import numpy
import numpy as np

### Selective import

In [0]:
from math import pi

## Numpy arrays

In [50]:
my_list = [1, 2, 3, 4]
my_list

[1, 2, 3, 4]

In [51]:
my_array = np.array(my_list)
my_array

array([1, 2, 3, 4])

In [52]:
my_2darray = np.array([[1,2,3],[4,5,6]])
my_2darray

array([[1, 2, 3],
       [4, 5, 6]])

### Selecting Numpy Array Elements

#### Subset

In [53]:
# Select item at index 1
my_array[1]

2

#### Slice

In [54]:
# Select items at index 0 and
my_array[0:2]

array([1, 2])

#### Subset 2D Numpy arrays

In [55]:
# my_2darray[rows, columns]
my_2darray[:,0]

array([1, 4])

### Numpy Array Operations

In [56]:
my_array > 3

array([False, False, False,  True])

In [57]:
my_array * 2

array([2, 4, 6, 8])

In [58]:
my_array + np.array([5, 6, 7, 8])

array([ 6,  8, 10, 12])

### Numpy Array Functions

In [59]:
# Get the dimensions of the array
my_array.shape

(4,)

In [60]:
# Append items to an array
my_3darray = my_2darray
np.append(my_3darray,[6,7,8])


array([1, 2, 3, 4, 5, 6, 6, 7, 8])

In [61]:
# Insert items in an array
np.insert(my_array, 1, 5)

array([1, 5, 2, 3, 4])

In [62]:
# Delete items in an array
np.delete(my_array,[1])

array([1, 3, 4])

In [63]:
# Mean of the array
np.mean(my_array)

2.5

In [64]:
# Median of the array
np.median(my_array)

2.5

In [0]:
# Correlation coefficient
# my_array.corrcoef()

In [66]:
# Standard deviation
np.std(my_array)

1.118033988749895