<a href="https://colab.research.google.com/github/jessicamadridmejia/Cheat-Sheets/blob/master/4_NumPy_Cheat_Sheet_Data_Analysis_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python For Data Science Cheat Sheet NumPy Basics

## NumPy
The NumPy library is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.


In [0]:
# Use the following import convention:
import numpy as np


## Creating Arrays

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
b = np.array([(1.5,2,3),(4,5,6)], dtype=float)
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [5]:
c = np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]], dtype=float)
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

### Initial Placeholders

In [6]:
# Create an array of zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
# Create an array of ones
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [8]:
# Create an array of evenly spaced values (step value)
d = np.arange(10,25,5)
d

array([10, 15, 20])

In [9]:
# Create an array of evenly spaced values (number of samples)
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [11]:
# Create a constant array
e = np.full((2,2),7)
e

array([[7, 7],
       [7, 7]])

In [13]:
# Create a 2x2 identity matrix
f = np.eye(2)
f

array([[1., 0.],
       [0., 1.]])

In [14]:
# Create an array with random values
np.random.random((2,2))

array([[0.51994308, 0.33315013],
       [0.56698156, 0.57914254]])

In [15]:
# Create an empty array
np.empty((3,2))

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

## Inspecting Your Array

In [16]:
# Array dimensions
a.shape

(3,)

In [17]:
# Length of array
len(a)

3

In [18]:
# Number of array dimensions
b.ndim

2

In [19]:
# Number of array elements
e.size

4

In [20]:
# Data type of array elements
b.dtype

dtype('float64')

In [21]:
# Name of data type
b.dtype.name

'float64'

In [22]:
# Convert an array to a different type
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

## Asking For Help

In [0]:
np.info(np.ndarray.dtype)

## Array Mathematics

### Arithmetic Operations

In [27]:
# Subtraction
g = a - b
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [28]:
# Subtraction
np.subtract(a,b)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [29]:
# Addition
b + a

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [30]:
# Addition
np.add(b,a)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [31]:
# Division
a / b

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [32]:
# Division
np.divide(a,b)

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [33]:
# Multiplicacion
a * b

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [34]:
# Multiplicacion
np.multiply(a,b)

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [35]:
# Exponentiation
np.exp(b)

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [36]:
# Square root
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [37]:
# Print sines of an array
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [38]:
# Element-wise cosine
np.cos(b)

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [39]:
# Element-wise natural logarithm
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [40]:
# Dot product
e.dot(f)

array([[7., 7.],
       [7., 7.]])

### Comparison

In [41]:
# Element-wise comparison
a == b

array([[False,  True,  True],
       [False, False, False]])

In [42]:
# Element-wise comparison
a < 2

array([ True, False, False])

In [43]:
# Array-wise comparison
np.array_equal(a,b)

False

### Aggregate Functions

In [44]:
# Array-wise sum
a.sum()

6

In [45]:
# Array-wise minimum value
a.min()

1

In [46]:
# Maximum value of an array row
b.max(axis=0)

array([4., 5., 6.])

In [47]:
# Cumulative sum of the elements
b.cumsum(axis=1)

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [48]:
# Mean
a.mean()

2.0

In [0]:
# Median
#b.median()

In [0]:
# Correlation coefficient
#a.corrcoed()

In [54]:
# Standard deviation
np.std(b)

1.5920810978785667

## Copying Arrays

In [57]:
# Create a view of the array with the same data
h = a.view()
h

array([1, 2, 3])

In [58]:
# Create a copy of the array
np.copy(a)

array([1, 2, 3])

In [59]:
# Create a deep copy of the array
h = a.copy()
h

array([1, 2, 3])

## Sorting Arrays

In [0]:
# Sort an array
a.sort()

In [0]:
# Sort the elements of an array's axis
c.sort(axis=0)

## Subsetting, Slicing, Indexing

### Subsetting

In [62]:
# Select the element at the 2nd index
a[2]

3

In [63]:
# Select the element at row 1 column 2 (equivalent to b[1][2])
b[1,2]

6.0

### Slicing

In [64]:
# Select items at index 0 and 1
a[0:2]

array([1, 2])

In [65]:
# Select items at rows 0 and 1 in column 1
b[0:2,1]

array([2., 5.])

In [66]:
# Select all items at row 0 (equivalent to b[0:1, :])
b[:1]

array([[1.5, 2. , 3. ]])

In [67]:
# Same as [1,:,:]
c[1,...]

array([[3., 2., 3.],
       [4., 5., 6.]])

In [69]:
# Reversed array a
a[: :-1]

array([3, 2, 1])

### Boolean Indexing

In [70]:
# Select elements from a less that 2
a[a<2]

array([1])

### Fancy Indexing

In [71]:
# Select elements (1,0),(0,1),(1,2) and (0,0)
b[[1,0,1,0],[0,1,2,0]]

array([4. , 2. , 6. , 1.5])

In [74]:
# Select a subset of the matrix's rows and columns
b[[1,0,1,0]][:,[0,1,2,0]]

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

## Array Manipulation

### Transposing Array

In [77]:
# Permute array dimensions
i = np.transpose(b)
i

array([[1.5, 4. ],
       [2. , 5. ],
       [3. , 6. ]])

In [78]:
# Permute array dimensions
i.T

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

### Changing Array Shape

In [79]:
# Flatten the array
b.ravel()

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [80]:
# Reshape, but don't change data
g.reshape(3,-2)

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

### Adding / Removing Elements

In [0]:
# Return a new array with shape (2,6)
#h.resize((2,6))

In [85]:
# Append items to an array
np.append(h,g)

array([ 1. ,  2. ,  3. , -0.5,  0. ,  0. , -3. , -3. , -3. ])

In [86]:
# Insert items in an array
np.insert(a,1,5)

array([1, 5, 2, 3])

In [87]:
# Delete items from an array
np.delete(a,[1])

array([1, 3])

### Combining Arrays

In [88]:
# Concatenate arrays
np.concatenate((a,d),axis=0)

array([ 1,  2,  3, 10, 15, 20])

In [89]:
# Stack arrays vertically (row-wise)
np.vstack((a,b))

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [90]:
# Stack arrays vertically (row-wise)
np.r_[e,f]

array([[7., 7.],
       [7., 7.],
       [1., 0.],
       [0., 1.]])

In [91]:
# Stack arrays horizontally (column-wise)
np.hstack((e,f))

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [92]:
# Create stacked column-wise arrays
np.column_stack((a,d))

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [93]:
# Create stacked column-wise arrays
np.c_[a,d]

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

### Splitting Array

In [94]:
# Split the array horizontally at the 3rd index
np.hsplit(a,3)

[array([1]), array([2]), array([3])]

In [95]:
# Split the array vertically at the 2nd index
np.vsplit(c,2)

[array([[[1.5, 2. , 1. ],
         [4. , 5. , 6. ]]]), array([[[3., 2., 3.],
         [4., 5., 6.]]])]

## I/O

### Saving & Loading On Disk

In [0]:
np.save('my_array',a)

In [0]:
np.savez('array.npz',a,b)

In [98]:
np.load('my_array.npy')

array([1, 2, 3])

### Saving & Loading Text Files

In [0]:
#np.loadtxt('myfile.txt')

In [0]:
#np.genfromtxt('my_file.csv', delimiter=',')

In [0]:
np.savetxt('myarray.txt',a,delimiter=' ')

## Data Types

In [104]:
# Signed 64-bit integer types
np.int64

numpy.int64

In [105]:
# Standard double-precision floating point
np.float32

numpy.float32

In [106]:
# Complex numbers represented by 128 floats
np.complex 

complex

In [107]:
# Boolean type storing TRUE and FALSE values
np.bool

bool

In [109]:
# Python object type
np.object

object

In [110]:
# Fixed-lenght string type
np.string_

numpy.bytes_

In [111]:
# Fixed-lenght unicode type
np.unicode_

numpy.str_